name: Build and Deploy - Development

on: 
  pull_request:


env:
  CONTAINER_NAME: sample-app
  ECR_REGISTRY: 629239571689.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: liamfit/sample-app
  IMAGE_TAG: 36cb4183b022314db7bdde3be1c6ce6677e9b605

jobs:
  test:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create some output
        id: build-image
        run: echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          env
          echo "${{ env.CONTAINER_NAME }}"
          echo "$CONTAINER_NAME"
          echo "${{ steps.build-image.outputs.image }}"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}
          task-definition: .aws/task-definition.json

      - name: Output task definition
        run: cat "${{ steps.task-def.outputs.task-definition }}"
